# Generated by Django 3.0.8 on 2020-07-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_user'),
        ('main', '0002_auto_20200727_1817'),
    ]

    operations = [
    ]
