# Generated by Django 3.0.8 on 2020-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20200728_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
