# Generated by Django 3.0.8 on 2020-07-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20200728_1806'),
        ('main', '0004_scenario_answer'),
    ]

    operations = [
    ]
