# Generated by Django 3.0.8 on 2020-07-29 22:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200729_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, validators=[main.models.check_validation_running]),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, validators=[main.models.check_validation_running]),
        ),
    ]
